// Firebase initialization for the Sheen web app.
//
// Project: sheen-alpha — your own Firebase project (created May 2026).
// The web config below was generated by Firebase Console when registering
// the web app; if you re-register the app, replace the whole block.
// Analytics' measurementId is intentionally omitted — we don't use
// Firebase Analytics, and including it pulls in extra bundle weight.
import { initializeApp } from 'firebase/app'
import {
  initializeAuth,
  indexedDBLocalPersistence,
  browserLocalPersistence,
  inMemoryPersistence,
  GoogleAuthProvider,
  OAuthProvider,
} from 'firebase/auth'
import { getFirestore } from 'firebase/firestore'
import { getFunctions } from 'firebase/functions'
import { getStorage } from 'firebase/storage'

const firebaseConfig = {
  apiKey:            'AIzaSyC0PaEQm6AbbL4-hTHiTmIW6chtJWm56c4',
  authDomain:        'sheen-alpha.firebaseapp.com',
  projectId:         'sheen-alpha',
  storageBucket:     'sheen-alpha.firebasestorage.app',
  messagingSenderId: '176127438166',
  appId:             '1:176127438166:web:8a8580cee98579843afaf7',
}

export const app = initializeApp(firebaseConfig)

// Auth — explicit persistence fallback chain instead of getAuth().
//
// On iOS Capacitor (WKWebView under capacitor://localhost) the default
// Firebase auth-state init reliably hangs because the SDK tries
// IndexedDB → falls into a Capacitor scheme edge case → never finishes
// initialising → onAuthStateChanged never fires → React SplashScreen
// gets stuck on "Loading…".
//
// Passing the persistence chain explicitly forces the SDK through a
// well-defined order: prefer IndexedDB, fall back to localStorage,
// finally in-memory (which always works but loses sign-in across app
// restarts). This pattern is recommended in Firebase docs for
// non-browser environments.
export const auth = initializeAuth(app, {
  persistence: [
    indexedDBLocalPersistence,
    browserLocalPersistence,
    inMemoryPersistence,
  ],
})

export const firestore = getFirestore(app)
export const storage   = getStorage(app)
// The Sheen Cloud Functions are deployed to us-central1 (default region).
// Switch to a regional instance only if the backend lives elsewhere.
export const functions = getFunctions(app)
export const googleProvider = new GoogleAuthProvider()

// Apple — uses the generic OAuthProvider with the 'apple.com' provider id.
// Requires "Apple" to be enabled in Firebase Console → Authentication →
// Sign-in providers, with a configured Services ID + Apple Developer team.
export const appleProvider = new OAuthProvider('apple.com')
appleProvider.addScope('email')
appleProvider.addScope('name')
