// Firebase initialization for the Sheen web app.
//
// Project: sheen-alpha — your own Firebase project (created May 2026).
// The web config below was generated by Firebase Console when registering
// the web app; if you re-register the app, replace the whole block.
// Analytics' measurementId is intentionally omitted — we don't use
// Firebase Analytics, and including it pulls in extra bundle weight.
import { initializeApp } from 'firebase/app'
import { getAuth, GoogleAuthProvider, OAuthProvider } from 'firebase/auth'
import { getFirestore } from 'firebase/firestore'
import { getFunctions } from 'firebase/functions'
import { getStorage } from 'firebase/storage'

const firebaseConfig = {
  apiKey:            'AIzaSyC0PaEQm6AbbL4-hTHiTmIW6chtJWm56c4',
  authDomain:        'sheen-alpha.firebaseapp.com',
  projectId:         'sheen-alpha',
  storageBucket:     'sheen-alpha.firebasestorage.app',
  messagingSenderId: '176127438166',
  appId:             '1:176127438166:web:8a8580cee98579843afaf7',
}

export const app       = initializeApp(firebaseConfig)
export const auth      = getAuth(app)
export const firestore = getFirestore(app)
export const storage   = getStorage(app)
// The Sheen Cloud Functions are deployed to us-central1 (default region).
// Switch to a regional instance only if the backend lives elsewhere.
export const functions = getFunctions(app)
export const googleProvider = new GoogleAuthProvider()

// Apple — uses the generic OAuthProvider with the 'apple.com' provider id.
// Requires "Apple" to be enabled in Firebase Console → Authentication →
// Sign-in providers, with a configured Services ID + Apple Developer team.
export const appleProvider = new OAuthProvider('apple.com')
appleProvider.addScope('email')
appleProvider.addScope('name')
